package pt.beeverycreative.updater;

import pt.beeverycreative.updater.utils.ExtensionFilter;
import pt.beeverycreative.updater.utils.Filename;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author beevc
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * enum for fast/easy OS checking
     */
    public enum Platform {

        WINDOWS, MACOS9, MACOSX, LINUX, OTHER
    }

    private DefaultComboBoxModel comboData;
    private String jLabel1_flag;
    private static Platform os;
    private String selectedFilePath;

    public String getJLabel1_flag() {

        return jLabel1_flag;
    }

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setTitle("BEEVERYCREATIVE BootLoader Updater");

        jButton2.setEnabled(false);
        jLabel1.setText(jLabel1_flag);
        jLabel4.setText("BEETHEFIRST-bootloader-4.1.0");
        //Default bootloader
        selectedFilePath = "tools/BEETHEFIRST-bootloader-4.1.0.bin";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectFileBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("BEEVERYCREATIVE Bootloader Updater");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Refresh" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText(" Port:");

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("bootloader 3.4.0 ");

        selectFileBtn.setText("Select Bootloader...");
        selectFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selectFileBtnMousePressed(evt);
            }
        });
        selectFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectFileBtn)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectFileBtn)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Update button
     * 
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jLabel1_flag = "Updating bootloader.";

        ArrayList<String> comPorts = new ArrayList<>();

        // EX: lpcprog.exe -control -wipe -bin BEETHEFIRST-bootloader-3.3.0-beta+20130930163800.bin COM5 230400 12000
        //String line2run = "tools/lpcprog.exe -control -wipe -bin tools/BEETHEFIRST-bootloader-3.3.0-beta+20130930163800.bin " + comboData.getSelectedItem().toString() + " 230400 12000";
        String exec = null;
        if (os == Platform.LINUX) {
            exec = "tools/linux/lpc21isp -control -wipe -bin "+ this.selectedFilePath+" /dev/" + comboData.getSelectedItem().toString() + " 230400 12000";
        } else if (os == Platform.MACOSX) {
            exec = "tools/macos/lpc21isp -control -wipe -bin "+ this.selectedFilePath+" /dev/" + comboData.getSelectedItem().toString() + " 230400 12000";
        } else if (os == Platform.WINDOWS) {
            exec = "tools/lpcprog.exe -control -wipe -bin "+ this.selectedFilePath+" " + comboData.getSelectedItem().toString() + " 230400 12000";
        }

        if (exec != null) {
            try {
                Process pr = Runtime.getRuntime().exec(exec);

                try (BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream()))) {
                    String line;
                    while ((line = in.readLine()) != null) {
                        if (line.toLowerCase().contains("err")) {
                            comPorts.clear();
                            //jTextArea1.append("Err02: Call Support");
                            break;
                        }

                        System.out.println(line);

                        if (line.toLowerCase().contains("now launching the brand new code")) {
                            //add com por
                            jLabel1.setText("Successfully updated.");
                            jLabel1_flag = "Successfully updated.";
                            jButton1.setEnabled(false);
                            jButton2.setEnabled(false);

                        }
                    }

                    pr.waitFor();

                    jComboBox2.setModel(comboData);

                    if (!jLabel1.toString().contains("Successfully")) {
                        jLabel1_flag = "Update failed.";
                        jLabel1.setText("Update failed.");
                        jButton1.setEnabled(true);
                        jButton2.setEnabled(true);
                    }
                }
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.err.println("Unable to determine the system platform to run the executable.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Refresh button
     * 
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pattern p = null;
        
        if (os == Platform.LINUX) {
            String re1 = "(tty)";	// Word 1
            String re2 = "((?:[a-z][a-z]+))";	// Word 2
            String re3 = "(\\d+)";	// Integer Number 1
            p = Pattern.compile(re1 + re2 + re3, Pattern.CASE_INSENSITIVE | Pattern.DOTALL);
        } else if (os == Platform.MACOSX) {
            String re1 = "(tty)";	// Word 1
            String re2 = "((?:[a-z][a-z]+))";	// Word 2
            String re3 = "(\\d+)";	// Integer Number 1
            p = Pattern.compile(re1 + re2 + re3, Pattern.CASE_INSENSITIVE | Pattern.DOTALL);
        } else if (os == Platform.WINDOWS) {
            String re1 = "((?:[a-z][a-z]+))";	// Word 1
            String re2 = "(\\d+)";	// Integer 1
            String re3 = " <USB Serial Port>";	// Fixed string
            p = Pattern.compile(re1 + re2 + re3, Pattern.CASE_INSENSITIVE | Pattern.DOTALL);
        }

        if (p != null) {
            ArrayList<String> comPorts = new ArrayList<>();

            try {
                Process pr = null;
                if (os == Platform.LINUX) {
                    pr = Runtime.getRuntime().exec("dmesg");
                } else if (os == Platform.MACOSX) {
                    pr = Runtime.getRuntime().exec("sudo dmesg");
                } else if (os == Platform.WINDOWS) {
                    pr = Runtime.getRuntime().exec("tools/Enumser.exe");
                }

                if (pr != null) {
                    try (BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream()))) {
                        String line;
                        while ((line = in.readLine()) != null) {
                            System.out.println(line);
                            Matcher m = p.matcher(line);
                            if (m.find()) {
                                String port;
                                String p1 = m.group(1);
                                String p2 = m.group(2);
                                
                                if (os != Platform.WINDOWS) {
                                    String p3 = m.group(3);
                                    port = p1 + p2 + p3;
                                    
                                    System.out.println("found:" + port);

                                    if (line.contains("disconnected") & comPorts.contains(port)) {
                                        comPorts.remove(port);
                                    }

                                    if (!comPorts.contains(port) & line.contains("attached")) {

                                        comPorts.add(port);
                                        jButton2.setEnabled(true);
                                    }
                                } else { //Windows
                                    port = p1 + p2;
                                    
                                    System.out.println("found:" + port);
                                    
                                    if (!comPorts.contains(port)) {
                                        comPorts.add(port);
                                        jButton2.setEnabled(true);
                                    }
                                    
                                }
                            }
                        }
                        if (comPorts.isEmpty()) {
                            comPorts.add("None found");
                            jButton2.setEnabled(false);
                        }
                        pr.waitFor();

                        comboData = new DefaultComboBoxModel(comPorts.toArray());
                        jComboBox2.setModel(comboData);
                        System.out.println("ok!");
                    }
                } else {
                    System.err.println("Error executing serial port reader command.");
                }
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                System.err.println("Error executing serial port reader command: " + ex.getMessage());
            }
        }  else {
            System.err.println("Unable to determine the system platform to run the executable.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void selectFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFileBtnActionPerformed

    private void selectFileBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFileBtnMousePressed
        String filePath = this.selectFile();

        if (filePath != null) {

            Filename fn = new Filename(filePath, '/', '.');

            jLabel4.setText(fn.filename());
            
            this.selectedFilePath = filePath;
        }
    }//GEN-LAST:event_selectFileBtnMousePressed

    /**
     * Select File to open. Supported type .bin
     *
     * @return path to file
     */
    private String selectFile() {
        File directory = new File(System.getProperty("user.home"));

        JFileChooser fc = new JFileChooser(directory);
        FileFilter defaultFilter;

        String[] extensions = {".bin"};
        fc.addChoosableFileFilter(defaultFilter = new ExtensionFilter(extensions, "BIN files"));
        fc.addChoosableFileFilter(new ExtensionFilter(".bin", "BIN files"));
        fc.setAcceptAllFileFilterUsed(true);
        fc.setFileFilter(defaultFilter);
        fc.setDialogTitle("Select a bootloader file...");
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        fc.setFileHidingEnabled(false);
        int rv = fc.showOpenDialog(this);
        if (rv == JFileChooser.APPROVE_OPTION) {
            //fc.getSelectedFile().getName();

            return fc.getSelectedFile().getAbsolutePath();
        } else {

            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Detects OS platform
        String OS = System.getProperty("os.name").toLowerCase();
        if (OS.contains("win")) {
            os = Platform.WINDOWS;
        } else if (OS.contains("mac")) {
            os = Platform.MACOSX;
        } else if (OS.contains("nix") || OS.contains("nux") || OS.contains("aix")) {
            os = Platform.LINUX;
        } else {
            os = Platform.OTHER;
        }

        /* Set the Nimbus look and feel */
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton selectFileBtn;
    // End of variables declaration//GEN-END:variables

}
